using System;
using System.Reflection;
using System.Runtime.InteropServices;
//------------------------------------------------------------------------------ 
// <auto-generated> 
//     This code was generated by a tool. 
//     Runtime Version:4.0.30319.34209 
// 
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------ 
[assembly: ComVisibleAttribute(false)]
[assembly: CLSCompliantAttribute(false)]
[assembly: AssemblyVersionAttribute("10.2.0.0")]
[assembly: AssemblyFileVersionAttribute("10.2.0.0")]
[assembly: AssemblyInformationalVersionAttribute("10.2.0.0")]
[assembly: AssemblyCopyrightAttribute("© Relativity")]
[assembly: AssemblyCompanyAttribute("Relativity ODA LLC")]
[assembly: AssemblyTitleAttribute("Relativity.SingleFileUpload")]
[assembly: AssemblyDescriptionAttribute("Relativity.SingleFileUpload")]
[assembly: AssemblyProductAttribute("Relativity.SingleFileUpload")]
