DECLARE @FID INT = 0

SELECT @FID = ArtifactID
FROM EDDSDBO.Folder AS F WITH (NOLOCK)
WHERE ArtifactID = @SupID

IF @FID = 0
BEGIN
	SELECT TOP 1  @FID = ArtifactID
	FROM EDDSDBO.FOLDER AS F WITH (NOLOCK)
	ORDER BY ARTIFACTID ASC
END

SELECT @FID AS FID