SELECT AVF.COLUMNNAME
FROM EDDSDBO.FIELD AS F WITH (NOLOCK)
INNER JOIN EDDSDBO.ARTIFACTVIEWFIELD AS AVF WITH (NOLOCK) ON F.ARTIFACTVIEWFIELDID = AVF.ARTIFACTVIEWFIELDID
WHERE F.FIELDARTIFACTTYPEID = 10
AND DISPLAYNAME IN ({0})