//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kCura.SingleFileUpload.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Javascript {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Javascript() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("kCura.SingleFileUpload.Resources.Javascript", typeof(Javascript).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script type=&quot;text/javascript&quot;&gt;
        ///    if (!openSFUErrorModal) {
        ///        function openSFUErrorModal() {
        ///            var w = 400;
        ///            var h = 335;
        ///            if ($(&apos;#uploadInfoDiv&apos;).length == 0) {
        ///                $(
        ///                    &apos;&lt;div id=&quot;uploadInfoDiv&quot; style=&quot;height: 335px&quot;&gt;&lt;iframe style=&quot;border:none;width:100%; height: 335px;&quot; src=&quot;/relativity/custompages/1738ceb6-9546-44a7-8b9b-e64c88e47320/sfu.html?AppID={APPID}&amp;errorFile={ERRORID}&quot;&gt;&lt;/iframe&gt;&lt;/div&gt;&apos;)
        ///                    .dialog({
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SingleFileUploadErrorsScript {
            get {
                return ResourceManager.GetString("SingleFileUploadErrorsScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //======================================================
        /////V 0.1
        /////======================================================
        ///var iframe = window.parent.parent.$(&quot;#_documentViewer__documentIdentifierFrame&quot;).contents();
        ///
        ///$(&apos;.reviewActionBarTop &gt; .reviewActionBarGroup:first &gt; .reviewActionBarActionButton:first&apos;).before(&apos;&lt;a class=&quot;reviewActionBarActionButton&quot; style=&quot;cursor: pointer;&quot; onclick=&quot;openSFUModal(false)&quot;&gt;Replace Document&lt;/a&gt;&apos;);
        ///
        ///if({{HasImages}})
        ///{
        ///    //addReplaceButton();
        ///}
        ///
        ///$(&apos;#replace_imag [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SingleFileUploadScript {
            get {
                return ResourceManager.GetString("SingleFileUploadScript", resourceCulture);
            }
        }
    }
}
